### ISSUE TITLE
Deprecate `__` in favor of `I18n::__`

### ISSUE THREAD

**Issue by enov** [kohana/core#526]
I am not sure if this is a good idea, so I want your input here.

kohana/kohana#31 has made the core to be loaded in `Kohana::modules()`, which makes the function `__` unavailable for `Kohana_Exception`.

We can either test its availability in `Kohana_Exception` or deprecate/replace `__` with `I18n::__`.

We can still leave `__` available for standard views, maybe it will be just an alias for `I18n::__`. `__` can be defined in bootstrap or we can keep it where it is now.

I don't know if I am making sense. You input is appreciated. Thanks!

**Comment by lenton** [comment]
I realise now what you've been trying to say about the __ function not being included, I thought you was talking about a different problem.

I'm in favour of moving the logic into a method (although I think a better name would be I18n::trans()) and then define the __ function in the bootstrap above the Kohana::methods() call.

**Comment by enov** [comment]
> I realise now what you've been trying to say about the __ function not being included, I thought you was talking about a different problem.

It's OK. But I think it's better to be a friendly developer than a good developer ;)

And btw, you need to define the function `__` below `Kohana::modules` call, as it uses the `I18n` class.

**Comment by lenton** [comment]
The function can be defined before Kohana::modules() without any problems, that way it can be used inside init.php files too.

**Comment by enov** [comment]
Alright then.

**Comment by enov** [comment]
But we need to replace occurrences of `__` with `I18n::translate` so that the `kohana/core` would be self contained and not relying on bootstrap. We can still keep `__` for Kohana users for their standard views.

**Comment by sergeyklay** [comment]
just `__` mb as alias for `I18n::translate`

**Comment by lenton** [comment]
I was thinking, maybe it's best to move the __() function back into the I18n class (still deprecated of course). It would make the upgrading process easier since users wouldn't have to add the function to their bootstrap; they wouldn't need to do anything.

**Comment by rjd22** [comment]
@lenton I don't agree because of the global scope pollution because of this feature. I have collisions because of this function with other libraries before.

**Comment by lenton** [comment]
@rjd22 I don't think that's much of a problem since it's rare and there are multiple ways for users to easily solve the problem:
- Kohana uses `if ( ! function_exists('__'))` so you could declare the library's __() function before Kohana does.
- Extend the Kohana_I18n class via the cascading filesystem to hide the __() function declaration.
- Remove the __()  function declaration directly from the core's Kohana_I18n class. It's deprecated and is due to be removed in a future version so it's ok.

The benefit we get is not worth the effort of forcing users to manually move the function to their bootstrap. We wouldn't have moved it out at all if it wasn't for another problem at the time which blinded our judgement.

**Comment by acoulton** [comment]
I agree with @rjd22 - I don't think the function definition should be in the Kohana_I18n file.

@lenton, only one of your solutions (declaring the library function first) works, and even then only some of the time. If the library is only sometimes required then loading it every request just to avoid the function conflict isn't ideal.

> Extend the Kohana_I18n class via the cascading filesystem to hide the __() function declaration.

But assuming you want the rest of `Kohana_I18n` you have to include that parent file at some point, which will declare the function.

> Remove the __() function declaration directly from the core's Kohana_I18n class

That's not possible if you are using composer or submodules (unless you're suggesting running a fork).

If we make it so that everything in core etc uses `I18n::__()` rather than `__()` then upgrading users have three options:
- Don't already use `__()` in your app? Do nothing.
- grep and replace **() with I18n::**() across your code.
- define __() in your bootstrap for legacy compatibility. 

I don't see any of them are a big deal.

Also I'm +1 on calling this `I18n::trans` or `I18n::tr()` or something a bit more obvious than `__()` if we're changing it anyway.

**Comment by lenton** [comment]
> But assuming you want the rest of Kohana_I18n you have to include that parent file at some point, which will declare the function.

I meant duplicate the whole class.

> That's not possible if you are using composer or submodules (unless you're suggesting running a fork).

You can't edit vendor code you've installed?

The last two solutions would work, you just may have to redo them after upgrading Kohana (which shouldn't be that often considering it's going to be removed in a future version).

> Don't already use __() in your app? Do nothing.
> grep and replace () with I18n::() across your code.
> define __() in your bootstrap for legacy compatibility.

__() is being deprecated, not removed; using it in 3.4 would still be considered legal so there's still going to be widespread use in 3rd party modules. Even if users don't have add it to their bootstrap, they are inevitably still going to install a module which does.

> Also I'm +1 on calling this I18n::trans or I18n::tr() or something a bit more obvious than __() if we're changing it anyway.

We have already moved it to the method I18n::tanslate() and replaced all uses of __() in the official modules (see the linked PRs).

Are we really going to force users to manually copy-and-paste the function into their bootstraps and then tell them to remove it later down the line? Let me remind you that users using a library which also defines __() is going to be very rare anyway. All of this could be seamless with **absolutely no upgrade tasks** regarding __(), apart from a warning of deprecation.

Think of the children.

**Comment by acoulton** [comment]
> You can't edit vendor code you've installed?

No, because it will get overwritten every time you run `composer install` - which won't just be when you update Kohana, it will (usually) also be any time you deploy anything. Unless you propose building in a post-deploy step in your script that copies your custom file over the one composer just put there. If you're running on more than one server you'd have to do something like that anyway. Ouch and yuk...

> Are we really going to force users to manually copy-and-paste the function into their bootstraps and then tell them to remove it later down the line? 

Yes. There's other changes they need to make to bootstrap already, so it's hardly a big deal. We can just refer them to a diff between 3.3 and 3.4 to work through and apply what they need. It's not like we're talking about changing other files all over the place. And it will kick-start the process of people realising that we don't recommend it and starting to use alternatives in any new code or anything they're updating.

> Think of the children.

Of all the 3.4 changes I think this is the one that will affect the children the absolute least.

**Comment by lenton** [comment]
Alright, I give in.

@acoulton Could you merge [the last PR](https://github.com/kohana/kohana/pull/63) and this issue would be completed and ready to be closed.

**Comment by acoulton** [comment]
@lenton done, thanks.
