### ISSUE TITLE
Request_Client_Internal doesn't log HTTP_Exception's 

### ISSUE THREAD

**Issue by rafi** [kohana/core#546]
If an internal request throws an uncaught exception, `Request_Client_Internal` will act differently for:
- `HTTP_Exception` - Calls `get_response()` which is just a shortcut to `::response()`.
- `Exception` - Calls `::_handler()` which calls `::log()` and `::response()`.

Bottom-line: `HTTP_Exception`'s aren't logged.
- What's the reason for not using `_handler()` in both situations?
- What's the purpose of `get_response()`?

**Comment by acoulton** [comment]
An `HTTP_Exception` is something you've consciously decided to throw from your code. It includes redirects, authentication required responses, validation failures, whatever. Kohana shouldn't (and doesn't) log them by default because it's up to you to decide whether you want to log the exception, the condition that made you decide to throw it, or nothing at all. If it started logging all the 404s, for example, you'd quickly get logs full of crawler requests, typos, etc - that's usually something you'd just want in your [apache|nginx|whatever] logs rather than in your application error logs.

An `Exception` however is something you've most likely forgotten or not expected to handle. It's an error case, and Kohana should (and does) log it so you can then identify the issue and make sure you handle it in a way that suits your application - which may be just letting it bubble, or converting it to an explicit 500/502/503 exception.

It's also important because if it's a subrequest, it's up to the calling code to decide whether a particular HTTP status code is expected or not, just like it would be if you were calling a remote API. It's your job to log that as required when you receive it. But because it's also important that subrequests look just like an HTTP request, an uncaught exception will come back to you as a 500 like any other - so Kohana logs the unexpected `Exception` in the child request context.

`HTTP_Exception::get_response` is used so that ["expected" exceptions](https://github.com/kohana/core/blob/3.3/master/classes/Kohana/HTTP/Exception/Expected.php) (301, 302, etc) just send the relevant headers and don't send an error page when thrown from the main request. ISTR at the time we thought that was something we might come back to as it didn't feel quite elegant.

Does that make sense?

**Comment by rafi** [comment]
Totally, great answer. Even included the internal-request scenario.

So the `HTTP_Exception_Expected` group of classes use a different response function to mostly validate the use-case, and if needed, propagate another exception. For the latter to work, it has to be outside of the try/catch-them-all in `Kohana_Exception::_handler()` which makes sure _unexpected_ exceptions response is handled correctly. This also means _all_ expected exceptions should handle their own human-error exceptions.

Wouldn't it be nicer if the trace optimization bits (xdebug/PHPUnit environments) would get their own function for re-usability sake?

**Comment by acoulton** [comment]
@rafi 

> This also means all expected exceptions should handle their own human-error exceptions

I'd say so, broadly, but it depends on usecase. There might be expected-ish (database server is offline) exceptions that you're happy to just let Kohana catch them, log them, and show your standard "uh-oh" page as if they were unexpected. OTOH if you have to talk to a flaky external API then you probably want to specifically handle when it's down - even if you ultimately choose to show the default error page, you may want to log outages in aggregate rather than log every failing call.

A more general rule might be that anywhere you catch and handle an `Exception`, if it's not possible to recover you should handle your own logging as required and throw a suitable HTTP_Exception rather than rethrowing the exception you caught.

> Wouldn't it be nicer if the trace optimization bits (xdebug/PHPUnit environments) would get their own function for re-usability sake?

There's a lot of bits in Kohana_Exception that it would be nice if they got their own function and/or class for resuability and testability.... feel free to start a PR :)

I'll close this as I think the issue you originally raised is dealt with - feel free to reopen if you wish.

**Comment by rafi** [comment]
@acoulton I made `Kohana_Exception` a little more flexible in terms of output format. https://paste.xinu.at/byl4d/
Is there a chance to accept anything like that in `3.4/develop`?

**Comment by acoulton** [comment]
Hi @rafi sorry it took me a bit of time to work out what's changed in your paste compared to what we have now.

IMO, adding support for different content types and templates for specific error codes is a useful new feature.

However, given the substantial changes required in that class to implement it, we'd also probably want to take the opportunity to rewrite the whole exception handler, response formatting and trace building etc from scratch. That class currently has an enormous number of responsibilities, helped slightly by the way you've extracted some extra methods but still very interdependent.

I'd imagine most of those methods are at least a whole non-static class of their own with unit tests. Some of the methods might merit more than one class. I'm not sure whether we'd then want to keep the existing static method interface as a thin facade over a new cleaner implementation - I'd lean to yes, even if deprecated, to reduce the API changes for end-users.

So yes to the idea, but we probably wouldn't accept the code to 3.4/develop with the structure you have at the moment. One of the others may disagree with me though.

**Comment by rafi** [comment]
It's a challenge bringing Kohana into the new era of cleaner code, specially with maintaining baby-steps and improving 3.4 while planning and with-holding the final vision for a whole re-write.

In the snippet I included, I haven't changed `Kohana_Exception` programmatic flow at all.
- Although the bit of [lines 63](https://paste.xinu.at/byl4d/#n63)-97 aren't flowing well with Kohana's minimal approach, it could split into a simpler function and be easily overridden. _e.g._ `$error_view = Kohana_Exception::get_error_view()`;
- The `handler()` improves CLI exceptions, much needed.
- The stack-strace optimization was split into `trace()`
- Lastly, added a convenience function `print_trace()` to stringify the optimized stack-trace because `Exception::getTraceAsString()` isn't available after mangling the stack-trace.

In my opinion these are pretty good improvements, and won't demand any special care when upgrading.
