### ISSUE TITLE
modules and composer - play together nicer

### ISSUE THREAD

**Issue by chrisgo** [kohana/core#674]
Wanted to see what the thoughts are regarding how we can make the 
1. `modules` and
2. `composer require` 

work together better.  

My setup is as follows:

```
src
  - php
    - web (this is the docroot)
      - application
      - modules
      - system
      - index.php (main kohana index.php file)
      - vendor (this is where composer lives)
      - composer.json
      - composer.lock
```

For example, Kohana has an email component that uses Swift mailer underneath

```
- modules
  - email
    - vendor
      - swiftmailer 
```

when doing a composer require swiftmailer (or even a dependency from other packages), 
the `vendor/composer/autoload_files.php` file gets another swiftmailer include

```
<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
    ...
);
```

which causes a duplicate class.  Hacking around with class_exists() solves the problem but a better solution is available?  

Some thoughts
1. I like the Kohana modules `init.php` and `config` concepts so hopefully we don't lose that
2. Move the Kohana modules into a composer-friendly structure under `vendor/kohana` 
3. Service Container (DI/IoC) kind of solve some of this by doing some sort of init (usually a closure before putting the instantiated module into the container)
4. Do namespaces help?

Thanks,
Chris

**Comment by gnovaro** [comment]
See this https://github.com/kohana/kohana/pull/46

**Comment by acoulton** [comment]
@chrisgo thanks for submitting this. 

Kohana 3.3 and all the official modules already fully support installation with composer, and from 3.4 the sample application in kohana/kohana uses composer instead of git submodules to reference the core and all the modules.

By default the modules will be installed to the `modules/name` path for compatibility, but you can easily force this back to the composer standard locations by adding to your composer.json:

```
"extra": {
  "installer-paths": {
     "vendor/{$vendor}/{$name}": ["type:kohana-module"]
    }
}
```

Note that nothing in Kohana actually cares about where the `/system` or `/modules` directories are - you can put any module/package anywhere so long as you put the correct path to it in your bootstrap.php.

I'm not sure which Kohana email module you're using - there are a few, and none are official - but the issue with getting a duplicate SwiftMailer is to do with the way they've set up that dependency. It would probably be best to ask them to also publish their module as a composer package and move the swiftmailer dependency into their own composer.json so that it doesn't need to be directly initialised by them.

Alternatively you could just remove the email module you're using and use SwiftMailer directly - in our projects we've found that once you have swiftmailer as a composer package it doesn't really need anything else.
